modbus:
  - id: modbus_component
    send_wait_time: 1000ms
    flow_control_pin: GPIO14

one_wire:
  - platform: gpio
    id: one_wire_1
    pin: GPIO27

sensor:
  - platform: dallas_temp
    id: temperature_sensor_1
    name: Dallas temperature 1
    one_wire_id: one_wire_1
    icon: mdi:thermometer
    index: 0
    update_interval: 15s
    filters:
      - lambda: return x + id(dallas_1_offset).state;
      - delta: 0.1
  - platform: dallas_temp
    id: temperature_sensor_2
    name: Dallas temperature 2
    one_wire_id: one_wire_1
    icon: mdi:thermometer
    index: 1
    update_interval: 15s
    filters:
      - lambda: return x + id(dallas_2_offset).state;
      - delta: 0.1
  - platform: dallas_temp
    id: temperature_sensor_3
    name: Dallas temperature 3
    one_wire_id: one_wire_1
    icon: mdi:thermometer
    index: 2
    update_interval: 15s
    filters:
      - lambda: return x + id(dallas_3_offset).state;
      - delta: 0.1